apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: prom
    app.kubernetes.io/name: grafana
  name: grafana-storage-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: storage-prom-grafana
