apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8s-project
  region: us-east-1

managedNodeGroups:
  - name: worker-group-1
    instanceType: t3.small
    desiredCapacity: 1
    labels: { role: worker1 }
    volumeSize: 15
    privateNetworking: true
